name: Django Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: mydatabase
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: eslam
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django pytest pytest-django psycopg2-binary Pillow

    - name: Run Django migrations
      working-directory: SoftwareProject
      env:
        DATABASE_URL: postgres://postgres:eslam@localhost:5432/mydatabase
      run: |
        python manage.py migrate

    - name: Run tests
      working-directory: SoftwareProject
      env:
        DATABASE_URL: postgres://postgres:eslam@localhost:5432/mydatabase
      run: |
        python manage.py test
